### ISSUE TITLE
The compiler seemingly doesn't recognise $denyallow or full-TLD blocks as valid

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/HostlistCompiler#42]
I've compared https://github.com/AdguardTeam/HostlistsRegistry/blob/main/filters/security/filter_12_DandelionSproutsAntiMalwareList/filter.txt with its upstream source at https://github.com/DandelionSprout/adfilt/blob/33f821aacaa1499a6a55c1aeca0e8baf76eaf728/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt, and apparently as many as 145 entries and comments seem to be missing from the former, for instance `://ww15.$denyallow=ww15.nl` and `||sbs^`.

Given the importance of such rules in *Dandelion Sprout's Anti-Malware List*, how it has been included in Hostlists Registry for some months now, and that `$denyallow` has been the AdGuard Team's recommended way to whitelist domains from entries for some time now, I hope this could be fixed.

**Comment by ameshkov** [comment]
I think `||sbs^` does not pass the validation, we do not allow wide rules like that (3 letters or less) with no additional modifiers that narrow it down. You can circumvent it by using a rule like that: `|*.sbs^`

Regarding `$denyallow`, this is a valid bug.

**Comment by DandelionSprout** [comment]
For that matter, the compiler doesn't seem to accept entries like `192.243.59.0/24` either, despite how I'm 60% sure that AGH accepts CIDR-formatted entries; and I have yet to test whether stuff like `/^192\.243\.59\.[0-9]{1,3}$/` would correctly block CNAME IPs.

**Comment by ameshkov** [comment]
@DandelionSprout AGH does not accept CIDR entries in the filter lists, just in the allowed/disallowed IPs only.
