### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by monsm** [AdguardTeam/HostlistCompiler#52]
this is my file,https://[raw.githubusercontent.com/monsm/XXKiller/mae/RMaker/make.cmd](https://raw.githubusercontent.com/monsm/XXKiller/mae/RMaker/make.cmd)
At the end of the execution of this file, after the execution of this line”hostlist-compiler -c ..\tmp%MAINFOLD%.json -o ..\..\%MAINFOLD%-adguard.txt“, the following will not be executed, what is the reason?

**Comment by Alex-302** [comment]
No info about errors. Add `echo`s and logging.
Also you may ask ChatGPT)
