### ISSUE TITLE
Strip `$all` single modifiers

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/HostlistCompiler#54]
At the momen, rules with single `$all` modifier are ignored, and the rules do not load to filter.
`$all`, `$all,third-party`, `$third-party,all` must be stripped.
For example:
`||example.com^$all` => `||example.com^`
`||example.com^$all,third-party` => `||example.com^`
`||example.com^$third-party,all` => `||example.com^`

**Comment by DandelionSprout** [comment]
I fully support this 100%.

I've proposed a fair few modifier removals before, including `$all` above, as well as `$doc` and `$network`.

**Comment by ameshkov** [comment]
But they are removed if you specify `RemoveModifiers` transformation in the config file:
https://github.com/AdguardTeam/HostlistCompiler?tab=readme-ov-file#remove-modifiers

**Comment by DandelionSprout** [comment]
I can only wildly guess that Alex intended it to apply to AdGuard's DNS engine, in regards to how entries are treated/supported in DNS lists by default, but that he got it wrong which repo to propose it in.

At around 75~80 actively worked-on repositories at https://github.com/orgs/AdguardTeam/repositories, even I have to guess at times which repo to suggest ideas at. 😅
