### ISSUE TITLE
Is there an easier way to filter out duplicate rules?

### ISSUE THREAD

**Issue by Shura23** [AdguardTeam/HostlistCompiler#71]
I have limited skills, but I have collected a lot of DNS filters, and many of them are definitely duplicate rules, or rules that have expired, and I hope to be able to get rid of them. I looked at HostlistCompiler
The instructions for use, I think are still complicated. I have an idea that after a user forks the project, they only need to add a DNS filter link to the configuration file to minimize the configuration items that the user needs to change, and use GitHub action to automatically execute and generate a rule file. If users only need to add rule links, it is undoubtedly much more convenient. So I would like to ask if such a tool can be provided? Also, you have one called DeadDomainsLinter
tool, if you follow my advice, then I want to incorporate this tool as well, users can choose whether to enable this tool, and after enabling this tool, some invalid domain names will also be removed in the process of duplicate checking. If you can provide such a tool, I would appreciate it

**Comment by xiulou23** [comment]
> > duplicate rules
> 
> Try:
> https://abpvn.com/ruleChecker/redundantRuleChecker.html

This site doesn't meet my requirements, I have millions of rules, my rules too many caused the site to crash

**Comment by Alex-302** [comment]
Filters compiler can do it
https://github.com/AdguardTeam/HostlistCompiler#-deduplicate
